version: '0'
services:
  ml_sokolov:
    # image: python:3.12-bookworm
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    container_name: ml_sokolov_content
    restart: always
    tty: true
    # command: sleep infinity
    volumes:
      # this is the *bind* mount
      - ../:/workspace
      # this mirrors volume defined in top-level `volumes` section
      - data:/data
volumes:
  data:
